version: "2"
linters:
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
      - (*github.com/spf13/cobra.Command).Help
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
      - (*database/sql.DB).Close
      - (*database/sql.Tx).Rollback
      - os.Unsetenv
