// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"database/sql"
)

type Event struct {
	ID          int32
	Dt          sql.NullTime
	Money       sql.NullInt32
	Description sql.NullString
}

type EventToTag struct {
	EventID sql.NullInt32
	TagID   sql.NullInt32
}

type Pattern struct {
	ID        int32
	KeyString sql.NullString
}

type PatternToTag struct {
	PatternID sql.NullInt32
	TagID     sql.NullInt32
}

type Tag struct {
	ID   int32
	Name sql.NullString
}
