// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package query

import (
	"context"
	"database/sql"
	"strings"
)

const createEvent = `-- name: CreateEvent :execresult
INSERT INTO event (
   dt, money, description
) VALUES (
  ?, ?, ?
)
`

type CreateEventParams struct {
	Dt          sql.NullTime
	Money       sql.NullInt32
	Description sql.NullString
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEvent, arg.Dt, arg.Money, arg.Description)
}

const createTag = `-- name: CreateTag :execresult
INSERT INTO tag (name) VALUES (?)
`

func (q *Queries) CreateTag(ctx context.Context, name sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTag, name)
}

const deleteEventByID = `-- name: DeleteEventByID :exec
DELETE FROM event
WHERE id = ?
`

func (q *Queries) DeleteEventByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEventByID, id)
	return err
}

const deleteTagByID = `-- name: DeleteTagByID :exec
DELETE FROM tag
WHERE id = ?
`

func (q *Queries) DeleteTagByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTagByID, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, dt, money, description FROM event
WHERE dt = ? AND money = ? AND description = ?
`

type GetEventParams struct {
	Dt          sql.NullTime
	Money       sql.NullInt32
	Description sql.NullString
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, arg.Dt, arg.Money, arg.Description)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Dt,
		&i.Money,
		&i.Description,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, dt, money, description FROM event
WHERE id = ?
`

func (q *Queries) GetEventByID(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Dt,
		&i.Money,
		&i.Description,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, name FROM tag WHERE name = ?
`

func (q *Queries) GetTag(ctx context.Context, name sql.NullString) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT event.id, event.dt, event.money, event.description, tag.name AS tags FROM event
LEFT OUTER JOIN event_to_tag ON event.id = event_to_tag.event_id
LEFT OUTER JOIN tag ON tag.id = event_to_tag.tag_id
WHERE event.dt BETWEEN ? AND ?
ORDER BY event.dt
`

type ListEventsParams struct {
	FromDt sql.NullTime
	ToDt   sql.NullTime
}

type ListEventsRow struct {
	ID          int32
	Dt          sql.NullTime
	Money       sql.NullInt32
	Description sql.NullString
	Tags        sql.NullString
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.FromDt, arg.ToDt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Dt,
			&i.Money,
			&i.Description,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsWithTags = `-- name: ListEventsWithTags :many
SELECT event.id, event.dt, event.money, event.description, tag.name AS tags FROM event
LEFT OUTER JOIN event_to_tag ON event.id = event_to_tag.event_id
LEFT OUTER JOIN tag ON tag.id = event_to_tag.tag_id
WHERE
  (event.dt BETWEEN ? AND ?) AND
  (tag.name IN (/*SLICE:tags*/?))
ORDER BY event.dt
`

type ListEventsWithTagsParams struct {
	FromDt sql.NullTime
	ToDt   sql.NullTime
	Tags   []sql.NullString
}

type ListEventsWithTagsRow struct {
	ID          int32
	Dt          sql.NullTime
	Money       sql.NullInt32
	Description sql.NullString
	Tags        sql.NullString
}

func (q *Queries) ListEventsWithTags(ctx context.Context, arg ListEventsWithTagsParams) ([]ListEventsWithTagsRow, error) {
	query := listEventsWithTags
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FromDt)
	queryParams = append(queryParams, arg.ToDt)
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsWithTagsRow
	for rows.Next() {
		var i ListEventsWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Dt,
			&i.Money,
			&i.Description,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeEvents = `-- name: ListOutcomeEvents :many
SELECT event.id, event.dt, event.money, event.description, tag.name AS tags FROM event
LEFT OUTER JOIN event_to_tag ON event.id = event_to_tag.event_id
LEFT OUTER JOIN tag ON tag.id = event_to_tag.tag_id
WHERE
  (event.dt BETWEEN ? AND ?) AND
  (event.money < 0)
ORDER BY event.dt
`

type ListOutcomeEventsParams struct {
	FromDt sql.NullTime
	ToDt   sql.NullTime
}

type ListOutcomeEventsRow struct {
	ID          int32
	Dt          sql.NullTime
	Money       sql.NullInt32
	Description sql.NullString
	Tags        sql.NullString
}

func (q *Queries) ListOutcomeEvents(ctx context.Context, arg ListOutcomeEventsParams) ([]ListOutcomeEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeEvents, arg.FromDt, arg.ToDt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutcomeEventsRow
	for rows.Next() {
		var i ListOutcomeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Dt,
			&i.Money,
			&i.Description,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeEventsWithTags = `-- name: ListOutcomeEventsWithTags :many
SELECT event.id, event.dt, event.money, event.description, tag.name AS tags FROM event
LEFT OUTER JOIN event_to_tag ON event.id = event_to_tag.event_id
LEFT OUTER JOIN tag ON tag.id = event_to_tag.tag_id
WHERE
  (event.dt BETWEEN ? AND ?) AND
  (tag.name IN (/*SLICE:tags*/?)) AND
  (event.money < 0)
ORDER BY event.dt
`

type ListOutcomeEventsWithTagsParams struct {
	FromDt sql.NullTime
	ToDt   sql.NullTime
	Tags   []sql.NullString
}

type ListOutcomeEventsWithTagsRow struct {
	ID          int32
	Dt          sql.NullTime
	Money       sql.NullInt32
	Description sql.NullString
	Tags        sql.NullString
}

func (q *Queries) ListOutcomeEventsWithTags(ctx context.Context, arg ListOutcomeEventsWithTagsParams) ([]ListOutcomeEventsWithTagsRow, error) {
	query := listOutcomeEventsWithTags
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FromDt)
	queryParams = append(queryParams, arg.ToDt)
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutcomeEventsWithTagsRow
	for rows.Next() {
		var i ListOutcomeEventsWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Dt,
			&i.Money,
			&i.Description,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tag
ORDER BY tag.id
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
