// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"database/sql"
)

type Event struct {
	ID          int64
	Dt          sql.NullTime
	Money       sql.NullInt32
	Description sql.NullString
}

type EventToTag struct {
	EventID sql.NullInt64
	TagID   sql.NullInt64
}

type Pattern struct {
	ID        int64
	KeyString sql.NullString
}

type PatternToTag struct {
	PatternID sql.NullInt64
	TagID     sql.NullInt64
}

type Tag struct {
	ID   int64
	Name sql.NullString
}
