name: Main

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make

    - name: Test
      run: |
        make test-setup PASSWORD=root_password
        make e2e-test
